"*.cram":
- attribute: pi
  value: ch12
- attribute: group
  value: hgi
- infer: sequence
  mapping:
    version: HD.VN
- attribute: cost
  value: 100000
  unit: gbp

"*":
- attribute: pi
  value: ch12
- attribute: group
  value: hgi
